language: node_js
node_js:
- "8"  # nodejs的版本
branches:
  only:
  - dev  # 设置自动化部署的源码分支
env:
  global:
    secure: B8EZUJQ9cJ0ocnYGtL/oWmqz0UNu9fKyXsnwm2AtOP5owpmCKAJEjf9ER0I9YsIQgfbPPn4rPObsUrHZUmfIC8/p2BQxWPzbl6P2++W5wc8/P7rtsqLsA31hnzLgbum/mMIt5Ri+1uSSZUUZS1Ri6eRycTgF/EHrxLhKnC717DSkkBHE10eB8mytQ0HdiZZ18Zeubs9QYByX7V2Zkj5H115HFC6pjyzmQDRSlIYfIzF4d1zeXcfTfjUfIF50jBAgMcSXRNvWjf8uH30iPpDUua46CU0vfufyoMylFIAd/ydIW5pBzsy2OfoYoeP5tDD/dLWABqEN6+kKDU/Cb9c+E2b7FkW6F1YTxhiV1dlxTZJABpSSe0AfRIePGfPnr80ljmRqtCwtx0jDsjuqmiOYcVUPsb09BDYRfud/gIyAoPm7Fd/0pXbx1+y9FhPOkK4QcyufneY8qah4ThLPaaqp186LSwdI3HKxvRUII7M9uO2ldFVeaIw1j4PUHAOgH+sG7V7Vkkg6oHYiqofrpJjlCvFJJgKIRFXz0SBE0aXfrJ1vwPVbINODFEG/YtM2I3Y5ZycwZyEEkv7F6uVkn8pgjtKO8sznv9/a4g8v/pHBW8YuK1IGHAlBO5AZevAn6dxvDzn0lid6WTlbYHnypT9HeVDiS8fHbxZ7Jy6Yu6Lo1sU=
before_install:
- export TZ='Asia/Shanghai'  # 设置时区
- npm install -g hexo
- npm install -g hexo-cli
before_script:
# 设置github账户信息
- git config --global user.name "feverrun" #设置github用户名
- git config --global user.email 209981505@qq.com #设置github用户邮箱
# github仓库操作
- sed -i'' "s~git@github.com:feverrun/feverrun.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/feverrun/feverrun.github.io.git~" _config.yml
# 安装依赖组件
install:
- npm install
# 执行的命令
script:
- hexo clean
- hexo generate
# 执行的成功后执行 
after_success:
- hexo deploy