language: node_js
node_js:
- "6"  # nodejs的版本
branches:
  only:
  - dev  # 设置自动化部署的源码分支
 
env:
  global:
    secure: N/UCgQegpudCXqjXr6rCT6xTYCUFUnfDoHuNN8/JEH2Vi/9D8bLbWfx8gQuB2wTwuksZhsA4ejca4E7bdX5qw31exKkKUmJihRNlqbMQkqFJpUVq9NpxYMVhgQrq/1JyReA4cMuTl/rfcmyEZfhD5JNEKghCwhoki4WQrFpT7gjMtWzGVO97xg0j/UP9bPphiB4hUtIcwEOVXmZYlGd4hiYVTmmPqgYPWUk+1OZTErK29lLY8CnzXWw51+y9nooMV0ZHQeH5WZaUq/ZsXHtDelT7otAdO5XOmb3v7+5DMzInX2GPbvKkvegE79/5h3ws7B/qPm6300rNdnqQ933NZcdz2bp+B8y7R8nkiR/9Bgf3dk8hRKOcbk39juy7DeTrJq6n4PglGWEmaS4495kwTAxSmGwbbbq1fyU8xoqvbuQi9orpUjDn8nQAHBfFAfWGaErVYkSgUA4ajlL7PHsENp92yzGari12m9LbSyqnRcrR2uGJjLxhv34jBRzC9lF+DJfFnKxJ7j5uSz2gag+Xxv4tocDy0mZxoDVuyRCHeX+Thkt+OmXYCR46/jyqiDLikn5cYKbYGzX/X9y+go2Oo7GmdySX6LVXJfrT1lVrKe8nJ00SsIQLOLuC0+9JugMc/CQ1Ki73y+XgvtlMWxpIwgKatTjsQ3oueU1vduXjgHQ=
 
before_install:
- export TZ='Asia/Shanghai'  
- npm install -g hexo
- npm install -g hexo-cli 

before_script:
# ------------------------------------------------
# 设置github账户信息 注意修改成自己的信息
# ------------------------------------------------
- git config --global user.name "feverrun"
- git config --global user.email 209981505@qq.com 
# ------------------------------------------------
# github仓库操作  注意将仓库修改成自己的
# ------------------------------------------------
- sed -i'' "s~git@github.com:feverrun/feverrun.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/feverrun/feverrun.github.io.git~" _config.yml
# 安装依赖组件
install:
- npm install
# 执行的命令
script:
- hexo clean
- hexo generate
# 执行的成功后执行 
after_success:
- hexo deploy
